update fbi to 2.10 version

diff --git a/support/fbi-2.07/fbgs b/support/fbi-2.07/fbgs
--- a/support/fbi-2.07/fbgs
+++ b/support/fbi-2.07/fbgs
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 #
 # PostScript/pdf viewer for the linux framebuffer console
@@ -15,10 +15,10 @@ trap "rm -rf $DIR" EXIT
 fbiopts=""
 gsopts=""
 passwd=""
-device="tiffpack"
+device="png16m"
 opt=1
 bell="off"
-helptext="
+helptext="\
 This program displays PostScript/pdf files using the linux framebuffer device.
 It is a simple wrapper script for GhostScript and fbi.
 
@@ -29,7 +29,7 @@ usage: fbgs [fbgs options] [fbi options] file
    -p    --password <arg>    a <password> passed to the PDF
    -fp   --firstpage <arg>   begins on the <arg> page
    -lp	 --lastpage <arg>    stops on the <arg> page
-   -c    --color             pages in color
+   -c    --(no)color         pages in color
    -l                        pages rendered with 100 dpi
    -xl                       pages rendered with 120 dpi
    -xxl                      pages rendered with 150 dpi
@@ -38,6 +38,7 @@ usage: fbgs [fbgs options] [fbi options] file
 Read the fbgs(1) and fbi(1) manpages for more details.
 "
 
+[ $# -ne 0 ] ||  set -- -h
 while test "$opt" = "1"; do
 	case "$1" in
 		# fbgs options
@@ -65,6 +66,10 @@ while test "$opt" = "1"; do
 			device="png16m"
 			shift
 			;;
+		--nocolor)
+			device="tiffpack"
+			shift
+			;;
 		-l)	gsopts="$gsopts -r100x100"
 			shift
 			;;
@@ -83,6 +88,7 @@ while test "$opt" = "1"; do
 		--autoup | --noautoup | \
 		--autodown | --noautodown | \
 		--fitwidth | --nofitwidth | \
+		--readahead | --noreadahead | \
 		-v | --verbose | --noverbose | \
 		-u | --random | --norandom | \
 		-1 | --once | --noonce)
@@ -108,6 +114,11 @@ while test "$opt" = "1"; do
 			;;
 	esac
 done
+
+if [ ! -f "$1" ]; then
+	echo "fbgs: cannot stat '$1': No such file or directory"
+	exit 1
+fi
 
 # run ghostscript
 echo
